# Importing Libraries and Dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('insurance.csv')

In [3]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.shape

(1338, 7)

In [5]:
df.isnull()             #There is no "Null/NaN" value in the Columns; Hence all are "False"

age    sex    bmi  children  smoker  region  charges
0     False  False  False     False   False   False    False
1     False  False  False     False   False   False    False
2     False  False  False     False   False   False    False
3     False  False  False     False   False   False    False
4     False  False  False     False   False   False    False
...     ...    ...    ...       ...     ...     ...      ...
1333  False  False  False     False   False   False    False
1334  False  False  False     False   False   False    False
1335  False  False  False     False   False   False    False
1336  False  False  False     False   False   False    False
1337  False  False  False     False   False   False    False

[1338 rows x 7 columns]

In [6]:
df.isnull().sum()                   #There is no "Null/NaN" value in the Columns

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

SINCE THERE IS NO "NAN/NULL" VALUE IN THE COLUMNS, WE DO NOT NEED TO DO FIND "MEASURE OF CENTRAL TENDENCY"

# 1. Replace_without any Encoding techniques

In [7]:
df1 = df.copy()
df2 = df.copy()
df3 = df.copy()

SEX column

In [8]:
df.sex.unique()             #to find the "Unique" Chr. in Column "sex"

array(['female', 'male'], dtype=object)

In [9]:
df.sex = df.sex.replace(['male', 'female'], [1,2])

In [10]:
df.head()

age  sex     bmi  children smoker     region      charges
0   19    2  27.900         0    yes  southwest  16884.92400
1   18    1  33.770         1     no  southeast   1725.55230
2   28    1  33.000         3     no  southeast   4449.46200
3   33    1  22.705         0     no  northwest  21984.47061
4   32    1  28.880         0     no  northwest   3866.85520

SMOKER column

In [11]:
df.smoker.unique()             #to find the "Unique" Chr. in Column "smoker"

array(['yes', 'no'], dtype=object)

In [12]:
df.smoker = df.smoker.replace(['yes', 'no'], [1,2])

In [13]:
df.head()

age  sex     bmi  children  smoker     region      charges
0   19    2  27.900         0       1  southwest  16884.92400
1   18    1  33.770         1       2  southeast   1725.55230
2   28    1  33.000         3       2  southeast   4449.46200
3   33    1  22.705         0       2  northwest  21984.47061
4   32    1  28.880         0       2  northwest   3866.85520

REGION column

In [14]:
df.region.unique()                #to find the "Unique" Chr. in Column "region"

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [15]:
df.region = df.region.replace(['northeast', 'northwest', 'southeast', 'southwest'], [1,2,3,4])

In [16]:
df.head()

age  sex     bmi  children  smoker  region      charges
0   19    2  27.900         0       1       4  16884.92400
1   18    1  33.770         1       2       3   1725.55230
2   28    1  33.000         3       2       3   4449.46200
3   33    1  22.705         0       2       2  21984.47061
4   32    1  28.880         0       2       2   3866.85520

# 2. Label Encoding through LOOP

In [17]:
df1.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()          #creating ML OBJECT/MODEL

In [19]:
from pandas.core.dtypes.common import is_numeric_dtype         #always check "IS DATATYPE IS NUMERIC OR NOT"

In [20]:
df1.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [21]:
for col in df1.columns:                      
    if is_numeric_dtype(df1[col]):
        continue
    
    df1[col] = le.fit_transform(df1[col])

In [22]:
df1.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

# 3. One-Hot Encoding through LOOP_creating DUMMY

In [23]:
df2.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

SEX column

In [24]:
columns = ['sex']      

for col in columns:
    one_hot = pd.get_dummies(df2[col],drop_first=True, prefix='sex')    #1st, create "DUMMY" and drop "1st DUMMY COLUMN"
    df2 = pd.concat([df2, one_hot], axis=1).drop(col,axis=1)              #also 'DROP' "sex" COLUMN

In [25]:
df2.head()

age     bmi  children smoker     region      charges  sex_male
0   19  27.900         0    yes  southwest  16884.92400         0
1   18  33.770         1     no  southeast   1725.55230         1
2   28  33.000         3     no  southeast   4449.46200         1
3   33  22.705         0     no  northwest  21984.47061         1
4   32  28.880         0     no  northwest   3866.85520         1

SMOKER column

In [26]:
columns = ['smoker']      

for col in columns:
    one_hot = pd.get_dummies(df2[col],drop_first=True, prefix='smoker')    #1st, create "DUMMY" and drop "1st DUMMY COLUMN"
    df2 = pd.concat([df2, one_hot], axis=1).drop(col,axis=1)              #also 'DROP' "smoker" COLUMN

In [27]:
df2.head()

age     bmi  children     region      charges  sex_male  smoker_yes
0   19  27.900         0  southwest  16884.92400         0           1
1   18  33.770         1  southeast   1725.55230         1           0
2   28  33.000         3  southeast   4449.46200         1           0
3   33  22.705         0  northwest  21984.47061         1           0
4   32  28.880         0  northwest   3866.85520         1           0

REGION column

In [28]:
columns = ['region']      

for col in columns:
    one_hot = pd.get_dummies(df2[col],drop_first=True, prefix='region')    #1st, create "DUMMY" and drop "1st DUMMY COLUMN"
    df2 = pd.concat([df2, one_hot], axis=1).drop(col,axis=1)              #also 'DROP' "region" COLUMN

In [29]:
df2.head()

age     bmi  children      charges  sex_male  smoker_yes  region_northwest  \
0   19  27.900         0  16884.92400         0           1                 0   
1   18  33.770         1   1725.55230         1           0                 0   
2   28  33.000         3   4449.46200         1           0                 0   
3   33  22.705         0  21984.47061         1           0                 1   
4   32  28.880         0   3866.85520         1           0                 1   

   region_southeast  region_southwest  
0                 0                 1  
1                 1                 0  
2                 1                 0  
3                 0                 0  
4                 0                 0

# 4. Ordinal Encoding

SEX column

In [30]:
gender = df3.sex.unique()                              #we get the "Unique" value of "sex"
gender

array(['female', 'male'], dtype=object)

In [31]:
from sklearn.preprocessing import OrdinalEncoder       #importing "ORDINAL ENCODER"

In [32]:
ordi = OrdinalEncoder(categories=[gender])               #creating OBJECT/MODEL for "sex"
ordi

OrdinalEncoder(categories=[array(['female', 'male'], dtype=object)])

In [33]:
encoded_values = ordi.fit_transform(df3[['sex']])          
encoded_values

array([[0.],
       [1.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [34]:
df3['sex'] = pd.DataFrame(encoded_values)        #converting "ENCODED values" to "DataFrame" and "UPDATE df3"

In [35]:
df3

age  sex     bmi  children smoker     region      charges
0      19  0.0  27.900         0    yes  southwest  16884.92400
1      18  1.0  33.770         1     no  southeast   1725.55230
2      28  1.0  33.000         3     no  southeast   4449.46200
3      33  1.0  22.705         0     no  northwest  21984.47061
4      32  1.0  28.880         0     no  northwest   3866.85520
...   ...  ...     ...       ...    ...        ...          ...
1333   50  1.0  30.970         3     no  northwest  10600.54830
1334   18  0.0  31.920         0     no  northeast   2205.98080
1335   18  0.0  36.850         0     no  southeast   1629.83350
1336   21  0.0  25.800         0     no  southwest   2007.94500
1337   61  0.0  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

SMOKER column 

In [36]:
cig = df3.smoker.unique()                              #we get the "Unique" value of "smoker"
cig

array(['yes', 'no'], dtype=object)

In [37]:
cig = ['no', 'yes']                                #we "Reorder" the "Unique" value of "smoker"

In [38]:
ordi1 = OrdinalEncoder(categories=[cig])               #creating OBJECT/MODEL for "smoker"
ordi1

OrdinalEncoder(categories=[['no', 'yes']])

In [39]:
encoded_values1 = ordi1.fit_transform(df3[['smoker']])          
encoded_values1

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [1.]])

In [40]:
df3['smoker'] = pd.DataFrame(encoded_values1)        #converting "ENCODED values" to "DataFrame" and "UPDATE df3"

In [41]:
df3

age  sex     bmi  children  smoker     region      charges
0      19  0.0  27.900         0     1.0  southwest  16884.92400
1      18  1.0  33.770         1     0.0  southeast   1725.55230
2      28  1.0  33.000         3     0.0  southeast   4449.46200
3      33  1.0  22.705         0     0.0  northwest  21984.47061
4      32  1.0  28.880         0     0.0  northwest   3866.85520
...   ...  ...     ...       ...     ...        ...          ...
1333   50  1.0  30.970         3     0.0  northwest  10600.54830
1334   18  0.0  31.920         0     0.0  northeast   2205.98080
1335   18  0.0  36.850         0     0.0  southeast   1629.83350
1336   21  0.0  25.800         0     0.0  southwest   2007.94500
1337   61  0.0  29.070         0     1.0  northwest  29141.36030

[1338 rows x 7 columns]

REGION column

In [42]:
location = df3.region.unique()                              #we get the "Unique" value of "region"
location

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [43]:
location = ['northeast', 'northwest', 'southeast', 'southwest']            #we "Reorder" the "Unique" value of "region"

In [44]:
ordi2 = OrdinalEncoder(categories=[location])               #creating OBJECT/MODEL for "region"
ordi2

OrdinalEncoder(categories=[['northeast', 'northwest', 'southeast',
                            'southwest']])

In [45]:
encoded_values2 = ordi2.fit_transform(df3[['region']])          
encoded_values2

array([[3.],
       [2.],
       [2.],
       ...,
       [2.],
       [3.],
       [1.]])

In [46]:
df3['region'] = pd.DataFrame(encoded_values2)        #converting "ENCODED values" to "DataFrame" and "UPDATE df3"

In [47]:
df3

age  sex     bmi  children  smoker  region      charges
0      19  0.0  27.900         0     1.0     3.0  16884.92400
1      18  1.0  33.770         1     0.0     2.0   1725.55230
2      28  1.0  33.000         3     0.0     2.0   4449.46200
3      33  1.0  22.705         0     0.0     1.0  21984.47061
4      32  1.0  28.880         0     0.0     1.0   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50  1.0  30.970         3     0.0     1.0  10600.54830
1334   18  0.0  31.920         0     0.0     0.0   2205.98080
1335   18  0.0  36.850         0     0.0     2.0   1629.83350
1336   21  0.0  25.800         0     0.0     3.0   2007.94500
1337   61  0.0  29.070         0     1.0     1.0  29141.36030

[1338 rows x 7 columns]